name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "AOC_SESSION_COOKIE=${{ secrets.AOC_SESSION_COOKIE }}" >> $GITHUB_ENV
          echo "AOC_USER_ID=${{ secrets.AOC_USER_ID }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Run update script
        run: |
          chmod +x .scripts/update_readme.sh
          .scripts/update_readme.sh

          # Check if README.md content has changed post-script
          echo "### Content of README.md after script execution ###"
          cat README.md
          echo "### Git diff of README.md ###"
          git diff README.md

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Ensure changes are staged if there's a modification
          git add README.md

          # Verify that the README.md file has been staged
          git status

          # Check for staged changes
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            echo "Changes detected, committing updates"
            git commit -m 'Update README'
            git push https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
          fi